name: cipher_eye
description: A Kreiseck project.

publish_to: 'none'

version: 1.0.8+8

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  flutter_riverpod: ^2.6.1
  firebase_core: ^4.10.0
  cloud_firestore: ^6.5.0
  firebase_auth: ^6.5.2
  firebase_ui_auth: ^3.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  crypto: ^3.0.7
  encrypt: ^5.0.3
  flutter_secure_storage: ^10.3.1
  local_auth: ^3.0.1

  jiffy: ^6.4.5
  device_info_plus: ^13.1.0
  http: ^1.6.0

  kreiseck_branding:
    git:
      url: https://github.com/mhmmdlkts/Kreiseck-Branding.git
      ref: main
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.0
  firebase_storage: ^13.4.6
  image: ^4.8.0
  pdf: ^3.12.0
  image_picker: ^1.2.3
  file_picker: ^12.0.0
  cunning_document_scanner: ^3.0.1
  crop_your_image: ^2.0.0
  share_plus: ^13.3.0
  path_provider: ^2.1.6
  pdfx: ^2.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^4.2.0
  firebase_storage_mocks: ^0.8.1

flutter:

  uses-material-design: true