name: cipher_eye
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_ui_auth: ^1.14.0
  jiffy: ^6.2.1
  geolocator: ^11.0.0
  device_info_plus: ^10.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true